export const DATA = {
    country: 'Deutschland',
    children: [
        {
            name: 'Land',
            level: 1,
            group: true,
            children: [
                {
                    name: 'Baden-Württemberg',
                    logo: true,
                    land: true,
                    level: 1,
                    area: '35,751.46 km²',
                    bundesratVotes: '6 (out of 69)',
                    density: '310/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 1,
                            value: 10879618,
                        },
                    ],
                },
                {
                    name: 'Berlin',
                    logo: true,
                    land: true,
                    level: 1,
                    total: 3520031,
                    area: '891.1 km²',
                    bundesratVotes: '4 (out of 69)',
                    density: '4088/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: 'Mitte',
                            logo: true,
                            level: 1,
                            value: 377965,
                        },
                        {
                            name: 'Friedrichshain-Kreuzberg',
                            level: 1,
                            value: 283974,
                        },
                        {
                            name: 'Pankow',
                            level: 1,
                            value: 402289,
                        },
                        {
                            name: 'Charlottenburg-Wilmersdorf',
                            level: 1,
                            value: 338831,
                        },
                        {
                            name: 'Spandau',
                            level: 1,
                            value: 242143,
                        },
                        {
                            name: 'Steglitz-Zehlendorf',
                            level: 1,
                            value: 307076,
                        },
                        {
                            name: 'Tempelhof-Schöneberg',
                            level: 1,
                            value: 348739,
                        },
                        {
                            name: 'Neukölln',
                            level: 1,
                            value: 329387,
                        },
                        {
                            name: 'Treptow-Köpenick',
                            level: 1,
                            value: 264999,
                        },
                        {
                            name: 'Marzahn-Hellersdorf',
                            level: 1,
                            value: 266684,
                        },
                        {
                            name: 'Lichtenberg',
                            level: 1,
                            value: 286246,
                        },
                        {
                            name: 'Reinickendorf',
                            level: 1,
                            value: 263597,
                        },
                    ],
                },
                {
                    name: 'Brandenburg',
                    logo: true,
                    land: true,
                    level: 1,
                    area: '29,478.63 km²',
                    bundesratVotes: '4 (out of 69)',
                    density: '83/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 1,
                            value: 2484826,
                        },
                    ],
                },
                {
                    name: 'Hessen',
                    logo: true,
                    land: true,
                    level: 1,
                    area: '21,100 km²',
                    bundesratVotes: '5 (out of 69)',
                    density: '300/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 1,
                            value: 6176172,
                        },
                    ],
                },
                {
                    name: 'Mecklenburg-Vorpommern',
                    logo: true,
                    land: true,
                    level: 1,
                    area: '23,174 km²',
                    bundesratVotes: '3 (out of 69)',
                    density: '69/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 1,
                            value: 1612362,
                        },
                    ],
                },
                {
                    name: 'Niedersachsen',
                    logo: true,
                    land: true,
                    level: 1,
                    area: '47,614.07 km²',
                    bundesratVotes: '6 (out of 69)',
                    density: '170/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 1,
                            value: 7926599,
                        },
                    ],
                },
                {
                    name: 'Nordrhein-Westfalen',
                    logo: true,
                    land: true,
                    level: 1,
                    area: '34,084.13 km²',
                    bundesratVotes: '6 (out of 69)',
                    density: '530/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 1,
                            value: 17865516,
                        },
                    ],
                },
                {
                    name: 'Rheinland-Pfalz',
                    logo: true,
                    land: true,
                    level: 1,
                    area: '19,854.21 km²',
                    bundesratVotes: '4 (out of 69)',
                    density: '202/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 1,
                            value: 4052803,
                        },
                    ],
                },
                {
                    name: 'Saarland',
                    logo: true,
                    land: true,
                    level: 1,
                    area: '2,570 km²',
                    bundesratVotes: '3 (out of 69)',
                    density: '390/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 1,
                            value: 995597,
                        },
                    ],
                },
                {
                    name: 'Sachsen-Anhalt',
                    logo: true,
                    land: true,
                    level: 1,
                    area: '20,451.58 km²',
                    bundesratVotes: '4 (out of 69)',
                    density: '110/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 1,
                            value: 2245470,
                        },
                    ],
                },
                {
                    name: 'Schleswig-Holstein',
                    logo: true,
                    land: true,
                    level: 1,
                    area: '15,763.18 km²',
                    bundesratVotes: '4 (out of 69)',
                    density: '180/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 1,
                            value: 2858714,
                        },
                    ],
                },
            ],
        },
        {
            name: 'Freistaat',
            level: 3,
            group: true,
            children: [
                {
                    name: 'Bayern',
                    logo: true,
                    land: true,
                    level: 3,
                    area: '70,550.19 km²',
                    bundesratVotes: '9 (out of 69)',
                    density: '185/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: 'Niederbayern',
                            logo: true,
                            level: 3,
                            value: 1212119,
                        },
                        {
                            name: 'Oberbayern',
                            logo: true,
                            level: 3,
                            value: 4588944,
                        },
                        {
                            name: 'Oberpfalz',
                            logo: true,
                            level: 3,
                            value: 1092339,
                        },
                        {
                            name: 'Oberfranken',
                            logo: true,
                            level: 3,
                            value: 1059358,
                        },
                        {
                            name: 'Mittelfranken',
                            logo: true,
                            level: 3,
                            value: 1738686,
                        },
                        {
                            name: 'Unterfranken',
                            logo: true,
                            level: 3,
                            value: 1306048,
                        },
                        {
                            name: 'Schwaben',
                            logo: true,
                            level: 3,
                            value: 1846020,
                        },
                    ],
                },
                {
                    name: 'Sachsen',
                    logo: true,
                    land: true,
                    level: 3,
                    total: 7926599,
                    area: '18,449.99 km²',
                    bundesratVotes: '4 (out of 69)',
                    density: '221/km2',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: 'Bautzen (Budyšin)',
                            level: 3,
                            value: 308350,
                        },
                        {
                            name: 'Erzgebirgskreis',
                            level: 3,
                            value: 1,
                        },
                        {

                            name: 'Görlitz (Zhorjelc)',
                            level: 3,
                            value: 262168,
                        },
                        {

                            name: 'Landkreis Leipzig',
                            level: 3,
                            value: 257596,
                        },
                        {

                            name: 'Meißen',
                            level: 3,
                            value: 243716,
                        },
                        {
                            name: 'Mittelsachsen',
                            level: 3,
                            value: 314591,
                        },
                        {
                            name: 'Nordsachsen',
                            value: 1,
                            level: 3,
                        },
                        {
                            name: 'Sächsische Schweiz-Osterzgebirge',
                            level: 3,
                            value: 245939,
                        },
                        {
                            name: 'Vogtlandkreis',
                            level: 3,
                            value: 233970,
                        },
                        {
                            name: 'Zwickau',
                            level: 3,
                            value: 327062,
                        },
                        {
                            name: 'Chemnitz',
                            level: 3,
                            value: 248645,
                        },
                        {
                            name: 'Dresden',
                            level: 3,
                            value: 547172,
                        },
                        {
                            name: 'Leipzig',
                            level: 3,
                            value: 587857,
                        },
                    ],
                },
                {
                    name: 'Thüringen',
                    logo: true,
                    land: true,
                    level: 3,
                    total: 2170714,
                    area: '16,171 km²',
                    bundesratVotes: '4 (out of 69)',
                    density: '130/km2',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: 'Altenburger Land',
                            level: 3,
                            value: 105557,
                        },
                        {
                            name: 'Eichsfeld',
                            level: 3,
                            value: 109576,
                        },
                        {
                            name: 'Gotha',
                            level: 3,
                            value: 138857,
                        },
                        {
                            name: 'Greiz',
                            level: 3,
                            value: 115419,
                        },
                        {
                            name: 'Hildburghausen',
                            level: 3,
                            value: 70612,
                        },
                        {
                            name: 'Ilm',
                            level: 3,
                            value: 116382,
                        },
                        {
                            name: 'Kyffhäuserkreis',
                            level: 3,
                            value: 87775,
                        },
                        {
                            name: 'Nordhausen',
                            level: 3,
                            value: 93084,
                        },
                        {
                            name: 'Saale-Holzland',
                            level: 3,
                            value: 90313,
                        },
                        {
                            name: 'Saale-Orla',
                            level: 3,
                            value: 92739,
                        },
                        {
                            name: 'Saalfeld-Rudolstadt',
                            level: 3,
                            value: 123891,
                        },
                        {
                            name: 'Schmalkalden-Meiningen',
                            level: 3,
                            value: 137973,
                        },
                        {
                            name: 'Sömmerda',
                            level: 3,
                            value: 77351,
                        },
                        {
                            name: 'Sonneberg',
                            level: 3,
                            value: 60300,
                        },
                        {
                            name: 'Unstrut-Hainich',
                            level: 3,
                            value: 113962,
                        },
                        {
                            name: 'Wartburgkreis',
                            level: 3,
                            value: 139003,
                        },
                        {
                            name: 'Weimarer Land',
                            level: 3,
                            value: 88507,
                        },
                        {
                            name: 'Eisenach',
                            level: 3,
                            value: 42800,
                        },
                        {
                            name: 'Weimar',
                            level: 3,
                            value: 65200,
                        },
                        {
                            name: 'Gera',
                            level: 3,
                            value: 94852,
                        },
                        {
                            name: 'Suhl',
                            level: 3,
                            value: 39200,
                        },
                        {
                            name: 'Jena',
                            level: 3,
                            value: 110321,
                        },
                        {
                            name: 'Erfurt',
                            level: 3,
                            value: 213699,
                        },
                    ],
                },
            ],
        },
        {
            name: 'Freie Hansestadt',
            level: 2,
            group: true,
            children: [
                {
                    name: 'Bremen',
                    logo: true,
                    land: true,
                    level: 2,
                    area: '326.73 km²',
                    bundesratVotes: '3 (out of 69)',
                    density: '1700/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 2,
                            value: 671489,
                        },
                    ],
                },
                {
                    name: 'Hamburg',
                    logo: true,
                    land: true,
                    level: 2,
                    area: '755.22 km²',
                    bundesratVotes: '3 (out of 69)',
                    density: '2500/km²',
                    timeZone: 'UTC+1 (CET)',
                    children: [
                        {
                            name: '',
                            level: 2,
                            value: 1787408,
                        },
                    ],
                },
            ],
        },
    ],
};
