export const DATA = [
    {
        name: 'Liverpool',
        shortName: 'LIV',
        country: 'England',
        shortCountryName: 'ENG',
        pot: 1,
    },
    {
        name: 'Chelsea',
        shortName: 'CHE',
        country: 'England',
        shortCountryName: 'ENG',
        pot: 1,
    },
    {
        name: 'Barcelona',
        shortName: 'BAR',
        country: 'Spain',
        shortCountryName: 'ESP',
        pot: 1,
    },
    {
        name: 'Manchester City',
        shortName: 'MCI',
        country: 'England',
        shortCountryName: 'ENG',
        pot: 1,
    },
    {
        name: 'Juventus',
        shortName: 'JUV',
        country: 'Italy',
        shortCountryName: 'ITA',
        pot: 1,
    },
    {
        name: 'Bayern Munich',
        shortName: 'BAY',
        country: 'Germany',
        shortCountryName: 'GER',
        pot: 1,
    },
    {
        name: 'Paris Saint-Germain',
        shortName: 'PSG',
        country: 'France',
        shortCountryName: 'FRA',
        pot: 1,
    },
    {
        name: 'Zenit Saint Petersburg',
        shortName: 'ZSP',
        country: 'Russia',
        shortCountryName: 'RUS',
        pot: 1,
    },
    {
        name: 'Real Madrid',
        shortName: 'MAD',
        country: 'Spain',
        shortCountryName: 'ESP',
        pot: 2,
    },
    {
        name: 'Atlético Madrid',
        shortName: 'ATM',
        country: 'Spain',
        shortCountryName: 'ESP',
        pot: 2,
    },
    {
        name: 'Borussia Dortmund',
        shortName: 'DOR',
        country: 'Germany',
        shortCountryName: 'GER',
        pot: 2,
    },
    {
        name: 'Napoli',
        shortName: 'NAP',
        country: 'Italy',
        shortCountryName: 'ITA',
        pot: 2,
    },
    {
        name: 'Shakhtar Donetsk',
        shortName: 'SHK',
        country: 'Ukraine',
        shortCountryName: 'UKR',
        pot: 2,
    },
    {
        name: 'Tottenham Hotspur',
        shortName: 'TOT',
        country: 'England',
        shortCountryName: 'ENG',
        pot: 2,
    },
    {
        name: 'Ajax',
        shortName: 'AJA',
        country: 'Netherlands',
        shortCountryName: 'NED',
        pot: 2,
    },
    {
        name: 'Benfica',
        shortName: 'BEN',
        country: 'Portugal',
        shortCountryName: 'POR',
        pot: 2,
    },
    {
        name: 'Lyon',
        shortName: 'LYO',
        country: 'France',
        shortCountryName: 'FRA',
        pot: 3,
    },
    {
        name: 'Bayer Leverkusen',
        shortName: 'B04',
        country: 'Germany',
        shortCountryName: 'GER',
        pot: 3,
    },
    {
        name: 'Red Bull Salzburg',
        shortName: 'RBS',
        country: 'Austria',
        shortCountryName: 'AUT',
        pot: 3,
    },
    {
        name: 'Olympiacos',
        shortName: 'OLY',
        country: 'Greece',
        shortCountryName: 'GRC',
        pot: 3,
    },
    {
        name: 'Club Brugge',
        shortName: 'BRU',
        country: 'Belgium',
        shortCountryName: 'BEL',
        pot: 3,
    },
    {
        name: 'Valencia',
        shortName: 'VAL',
        country: 'Spain',
        shortCountryName: 'ESP',
        pot: 3,
    },
    {
        name: 'Inter Milan',
        shortName: 'INT',
        country: 'Italy',
        shortCountryName: 'ITA',
        pot: 3,
    },
    {
        name: 'Dinamo Zagreb',
        shortName: 'DZA',
        country: 'Croatia',
        shortCountryName: 'CRO',
        pot: 3,
    },
    {
        name: 'Lokomotiv Moscow',
        shortName: 'LMO',
        country: 'Russia',
        shortCountryName: 'RUS',
        pot: 4,
    },
    {
        name: 'Genk',
        shortName: 'GNK',
        country: 'Belgium',
        shortCountryName: 'BEL',
        pot: 4,
    },
    {
        name: 'Galatasaray',
        shortName: 'GAL',
        country: 'Turkey',
        shortCountryName: 'TUR',
        pot: 4,
    },
    {
        name: 'RB Leipzig',
        shortName: 'RBL',
        country: 'Austria',
        shortCountryName: 'AUT',
        pot: 4,
    },
    {
        name: 'Slavia Prague',
        shortName: 'SLP',
        country: 'Czechia',
        shortCountryName: 'CZE',
        pot: 4,
    },
    {
        name: 'Crvena Zvezda Belgrad',
        shortName: 'CSB',
        country: 'Serbia',
        shortCountryName: 'SRB',
        pot: 4,
    },
    {
        name: 'Atalanta',
        shortName: 'ATT',
        country: 'Italy',
        shortCountryName: 'ITA',
        pot: 4,
    },
    {
        name: 'Lille',
        shortName: 'LIL',
        country: 'France',
        shortCountryName: 'FRA',
        pot: 4,
    },
];




